
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import Header from "./pages/header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Aplication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="">
          <Header/>
          <main className="px-10 md:px-18">{children}</main>
        </div>
      </body>
    </html>
  );
}
