
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import Header from "./pages/header/page";
import ScrollToTopButton from "./pages/ScrollToTop/page";
import Footer from "./pages/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Aplication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="">
          <Header/>
          <main className="md:px-24 px-4 lg:px-36 min-h-screen mb-8">{children}</main>
          <Footer/>
          <ScrollToTopButton/>
        </div>
      </body>
    </html>
  );
}
